Первая версия модели на PyTorch Lightning
saridormi/commit_message_generation pull request #1
Opened 2020-11-10 09:17 UTC by saridormi

## Краткий комментарий

### Текущее состояние

Код для обучения модели ([`training/trainer_main.py`](https://github.com/saridormi/commit_message_generation/blob/lightning-dev/training/trainer_main.py)) с флагом [`fast_dev_run`](https://pytorch-lightning.readthedocs.io/en/latest/debugging.html#fast-dev-run) (по 1 батчу на train, val и test) работает без ошибок.

### Основные изменения
В датасете:
* Точно отбрасываются примеры, где диффы и сообщения больше заданной длины (по количеству токенов, которые получаются просто разделением по пробелам)
* Для работы с датасетом используется `LightningDataModule`

В декодере:
* Используется свой [Embedding](https://pytorch.org/docs/stable/generated/torch.nn.Embedding.html) слой
* Вместо прошлого механизма внимания используется [MultiheadAttention из PyTorch](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html)

В модели в целом:
* Для работы с моделью используется `LightningModule`
* На этапе тестирования сейчас используется только greedy подход

В метриках:
* Для подсчета accuracy считается количество равных элементов между тензорами с токенами (padding не учитывается)
* Для подсчета BLEU используется [функция из PyTorch Lightning](https://pytorch-lightning.readthedocs.io/en/latest/metrics.html#bleu-score-func)

### TODO и возможные проблемы

* В декодере после каждого шага модели подается только один предыдущий токен - нужно ли подавать все предыдущие? 
* Стоит ли считать accuracy на тензорах с токенами - длина предсказаний может не совпадать с длиной таргета, также токен может быть частью слова, а не целым?
* Какое значение параметра `reduction` использовать в [loss-е](https://pytorch.org/docs/stable/nn.functional.html?highlight=nll_loss#torch.nn.functional.nll_loss) - 'sum' или 'mean'?
* Реализовать beam search

2020-11-10 13:44 UTC, SokolovYaroslav commented
Поставь меня ревьюером :)

2020-11-10 13:47 UTC, SokolovYaroslav commented
для этого мб придется сделать меня контрибьютором репозитория

2020-11-12 16:16 UTC, SokolovYaroslav commented
> Код для обучения модели (training/trainer_main.py) с флагом fast_dev_run (по 1 батчу на train, val и test) работает без ошибок.
А в обычном режиме с ошибками или это просто сказано, типа работает?

> Какое значение параметра reduction использовать в loss-е - 'sum' или 'mean'?
О, это интересный вопрос. Я бы предложил сумму. Тогда возможно придётся поподбирать оптимальный learning_rate

2020-11-12 16:18 UTC, SokolovYaroslav commented
Стоит завести `requirements.txt` и туда записать необходимые библиотеки с текущей версией (то есть через `==`, а не `>=`). Потому что PL часто ломает зависимости при обновлениях.

2020-11-12 16:45 UTC, SokolovYaroslav requested changes

2020-11-12 16:45 UTC, SokolovYaroslav commented on Config.py
> +def make_reproducible(seed: int, make_cuda_reproducible: bool) -> None:
В PL есть `seed_everything`

2020-11-12 16:45 UTC, SokolovYaroslav commented on Config.py
> +        torch.backends.cudnn.benchmark = False
А вообще я бы предложил переехать на [hydra](http://hydra.cc/docs/intro/#!) для конфигов. Можешь поизучать, если будут вопросы -- пиши :)

2020-11-12 16:45 UTC, SokolovYaroslav commented on Config.py
> +        torch.backends.cudnn.benchmark = False
Но там нам не нужно прям кучу функциональности. Просто конфигурации на `yaml` и через декоратор прикрутить его

2020-11-12 16:45 UTC, SokolovYaroslav commented on metrics/MyAccuracyMetric.py
> +class MyAccuracyMetric(Metric):
Может без `My` сделать?)))

2020-11-12 16:45 UTC, SokolovYaroslav commented on training/trainer_main.py
> +trainer.test(datamodule=dm)
Еще из модных штук можно `WandBLogger` взять, который уже есть в PL. Тогда будет удобно делиться результатами запусков и они никуда не пропадут

2020-11-12 16:45 UTC, SokolovYaroslav commented on metrics/MyBleuMetric.py
> +        return self.bleu / self.total
Может в один файл с Accuracy запихать? `metrics` тип

2020-11-12 16:45 UTC, SokolovYaroslav commented on Config.py
> +import os
Вообще в питоне же обычно файлы в Снейк кейсе пишут, разве нет?

2020-11-12 16:45 UTC, SokolovYaroslav commented
> Реализовать beam search

Пока предлагаю забить

2020-11-12 16:49 UTC, SokolovYaroslav commented
Было бы Мега удобно мне (и всем другим людям, которые захотят воспроизвести обучение) сделать конфигурацию в пайчарме и сохранить её в проекте (если ты сама используешь пайчарм :))

Это можно сделать либо настроив хорошенько .gitignore (по этому поводу можешь писать мне, я спрошу у тех, кто шарит) и добавлять .idea в репо.

Либо я в конфигурации запуска увидел галочку `Store as project file` сверху справа

2020-11-12 16:51 UTC, SokolovYaroslav commented
> Стоит ли считать accuracy на тензорах с токенами - длина предсказаний может не совпадать с длиной таргета, также токен может быть частью слова, а не целым?

Ну если токенизировать таргет, то можно и стоит так делать, да. А как иначе? Есть какой-то честный токенизатор, который лучше робертовского?

2020-11-12 16:53 UTC, SokolovYaroslav commented on training/trainer_main.py
> +config = Config()
Обернуть бы в `if __name__ == "__main__"`

2020-11-12 16:55 UTC, SokolovYaroslav commented
> В декодере после каждого шага модели подается только один предыдущий токен - нужно ли подавать все предыдущие?

Только если через аттеншон. А так по одному, да

2020-11-12 17:07 UTC, SokolovYaroslav commented
> Вместо прошлого механизма внимания используется MultiheadAttention из PyTorch

Хорошее решение :) Q,K,V используешь как в статье, так что всё правильно

2020-11-13 10:10 UTC, saridormi commented
> > Код для обучения модели (training/trainer_main.py) с флагом fast_dev_run (по 1 батчу на train, val и test) работает без ошибок.
> 
>  А в обычном режиме с ошибками или это просто сказано, типа работает?

Да, это просто чтобы быстро понять, что все этапы отработали без проблем

> > Стоит ли считать accuracy на тензорах с токенами - длина предсказаний может не совпадать с длиной таргета, также токен может быть частью слова, а не целым?
> 
> Ну если токенизировать таргет, то можно и стоит так делать, да. А как иначе? Есть какой-то честный токенизатор, который лучше робертовского?

Просто в прошлой версии кода accuracy считалась по уже декодированным строкам, я не очень поняла, есть ли в этом необходимость, подумала, что на токенах может получиться немного другой результат из-за Byte-Pair-Encoding (например, какие-то части слов совпадут, а целые слова нет), но если это не так важно, то получается определенно быстрее :)

> Стоит завести `requirements.txt` и туда записать необходимые библиотеки с текущей версией (то есть через `==`, а не `>=`). Потому что PL часто ломает зависимости при обновлениях.

> Было бы Мега удобно мне (и всем другим людям, которые захотят воспроизвести обучение) сделать конфигурацию в пайчарме и сохранить её в проекте (если ты сама используешь пайчарм :))
> 
> Это можно сделать либо настроив хорошенько .gitignore (по этому поводу можешь писать мне, я спрошу у тех, кто шарит) и добавлять .idea в репо.
> 
> Либо я в конфигурации запуска увидел галочку `Store as project file` сверху справа

Хорошо, добавлю `requirements.txt` и посмотрю, что получается с галочкой `Store as project file` :) 

> А вообще я бы предложил переехать на [hydra](http://hydra.cc/docs/intro/#!) для конфигов. Можешь поизучать, если будут вопросы -- пиши :)

> Еще из модных штук можно `WandBLogger` взять, который уже есть в PL. Тогда будет удобно делиться результатами запусков и они никуда не пропадут

Звучит интересно, попробую разобраться! 

Остальные штуки тогда поправлю.

Спасибо большое за советы!

2020-11-16 19:21 UTC, SokolovYaroslav requested changes
По поводу остального кода, в котором содержится основная логика модели: кажется надо как-то вместе засесть и я бы послушал, как всё работает, потому что так очень сложно разобраться сразу во всём

2020-11-16 19:22 UTC, SokolovYaroslav commented
Где в итоге `seed_everything` находится?

2020-11-17 08:50 UTC, saridormi commented
> По поводу остального кода, в котором содержится основная логика модели: кажется надо как-то вместе засесть и я бы послушал, как всё работает, потому что так очень сложно разобраться сразу во всём

Да, конечно, можем договориться на какое-то удобное время :)

> А почему такая старая версия?

Это вроде последняя версия hydra-core, или я чего-то не понимаю?

> Где в итоге seed_everything находится?

Ой, я забыла про это. Спасибо :)

> Мб сделать все кончики в одном файле? А то так как-то разбросанно и надо бегать по файлам

Думаю, так и правда будет лучше, поменяю


А остальные баги поправлю и добавлю type hints

Спасибо еще раз!

2020-11-17 09:39 UTC, SokolovYaroslav commented
> Это вроде последняя версия hydra-core, или я чего-то не понимаю?

Согласен, что-то я не туда посмотрел

2020-11-26 15:20 UTC, SokolovYaroslav commented
Может вмерджим?
Кажется надо зафиксировать это, так как мы видимо принципиально ничего не починим :)

2020-11-26 15:45 UTC, merged